### ISSUE TITLE
Feature: User can view motivational quote and random animal image

### ISSUE THREAD

**Issue by mduguil** [mduguil/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view motivational quote and random animal image

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a button based on their mood and a quote/advice will be displayed

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Home3](https://user-images.githubusercontent.com/76453386/114616308-89a23c80-9c5b-11eb-8fa7-19ba85a70407.png)
![sad](https://user-images.githubusercontent.com/76453386/114613494-41cde600-9c58-11eb-8dc0-b61881f517f5.png)
![homephone](https://user-images.githubusercontent.com/76453386/114755139-2f15e880-9d0e-11eb-901e-7c8403b49ce6.png)
![sadphone](https://user-images.githubusercontent.com/76453386/114755150-31784280-9d0e-11eb-8d16-d4c277f22c74.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Set background image/color
- [x] Create navigation bar on bottom of screen
- [x] Add list icon
- [x] Set Page Title
- [x] Set Page slogan
- [x] Create "sad life" button
- [x] Create "happy times" button
- [x] Add button Description
- [x] Add "click"  listener to buttons
- [x] Create Sad view
   - [x]  Add random animal image
   - [x] Add random quote
 - [x]  Add Home icon to navbar
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
