### ISSUE TITLE
Feature: User can view advice

### ISSUE THREAD

**Issue by mduguil** [mduguil/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view advice

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User clicks the Happy mood option and a random advice will be generated.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![happyd](https://user-images.githubusercontent.com/76453386/114927807-bdf63400-9de6-11eb-91fc-21a48a3e0f14.png)
![happyphone](https://user-images.githubusercontent.com/76453386/114927809-be8eca80-9de6-11eb-98b0-2c1de824b06e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

 
- [x] Create happy view
   - [x] Add 'click' listener to happy button
   - [x] Generate random quote
   - [x] Add random quote to dom tree
   - [x] Hide home view
   - [x] Style happy view
- [x]  Add home icon to navbar
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
