### ISSUE TITLE
Feature: User can like & dislike a quote

### ISSUE THREAD

**Issue by mduguil** [mduguil/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can like & dislike a quote

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![happy](https://user-images.githubusercontent.com/76453386/114616734-10efb000-9c5c-11eb-9ed1-b3707b03fb97.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create "Like" button
- [x] Create "Dislike" button"
- [x]  Style button
- [x] Sad-view
   - [x]  Layout button to bottom of quote
   - [x] Add "click" listener to like button
      - [x] If like button is clicked, show encouraging phrase
   - [x] Add "click" listener to dislike button
      - [x]  if disliked button is clicked generate new quote
- [x] Happy-view
   - [x]  Layout button to bottom of advice
   - [x] Add "click" listener to like button
      - [x] If like button is clicked, show encouraging phrase
   - [x] Add "click" listener to dislike button
      - [x]  if disliked button is clicked generate new advice
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
