### ISSUE TITLE
Feature: User can submit a “How I am feeling today” entry

### ISSUE THREAD

**Issue by mduguil** [mduguil/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can submit a “How I am feeling today” entry

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![form](https://user-images.githubusercontent.com/76453386/114616785-2238bc80-9c5c-11eb-9b6b-5902058cee2e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an empty entry view
- [x] Create placeholder text for empty entries
- [x] Create "New Entry" button
- [x] "How I'm feeling" Form 
   - [x] Add "name" input 
   - [x] Add "Mood" input
   - [x] Add "How are you feeling today?" textarea
      - [x] Create placeholder text
   - [x] Make all inputs in form required
   - [x] Create submit button
- [x] Listen for the 'submit' event on feeling form
   - [x] Create data object
   - [x] put input values into the data object
   - [x] Reset form input
- [x] Verify entries are saved to local storage
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
