### ISSUE TITLE
Feature: User can view a list of their entries

### ISSUE THREAD

**Issue by mduguil** [mduguil/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of their entries

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![entries](https://user-images.githubusercontent.com/76453386/114616825-311f6f00-9c5c-11eb-895c-566b98ff61af.png)
![entry-list](https://user-images.githubusercontent.com/76453386/115637182-682cfa80-a2c4-11eb-8f2b-887db104c19f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create DOM tree for new entry
   - [x] Attach values from entry to DOM
   - [x] Append tree to entries list view
   - [x] Add date to entry
   - [x] Ensure entries show latest first
- [x] Style entries
   - [x] Center entries list
   - [x] Ensure "New Entry" button is at the top of the list
- [x] Ensure submitting form shows updated entries
- [x] Remove placeholder if there are entries
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
